module.exports = {
  apps: [
    {
      name: "monopoly-backend",
      script: "./backend/dist/main.js",
      cwd: "./backend",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: process.env.PORT || 3000,
      },
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: "monopoly-frontend",
      script: "serve",
      args: `-s dist -l ${process.env.FRONTEND_PORT || 3001}`,
      cwd: "./frontend",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: process.env.FRONTEND_PORT || 3001,
      },
      error_file: "./logs/frontend-error.log",
      out_file: "./logs/frontend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "300M",
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
  ],
};
